name: Update Leaderboard in README

on:
  push:
    paths:
      - 'monthly_submissions/**'

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Update Leaderboard in README.md
        run: |
          COMMITTER=$(git log -1 --pretty=format:'%an')
          MONTH=$(date +'%Y-%m')
          README_FILE="README.md"

          # Extract current leaderboard
          LEADERBOARD=$(awk '/<!-- LEADERBOARD_START -->/{flag=1;next}/<!-- LEADERBOARD_END -->/{flag=0}flag' $README_FILE)

          # Check if the month entry already exists
          if ! echo "$LEADERBOARD" | grep -q "$MONTH"; then
            NEW_ENTRY="| $MONTH | $COMMITTER |"
            UPDATED_LEADERBOARD="$LEADERBOARD\n$NEW_ENTRY"
          elif ! echo "$LEADERBOARD" | grep -q "$COMMITTER"; then
            UPDATED_LEADERBOARD=$(echo "$LEADERBOARD" | sed "/$MONTH/ s/$/ $COMMITTER,/")
          else
            UPDATED_LEADERBOARD="$LEADERBOARD"
          fi

          # Replace the leaderboard in README
          awk -v new_leaderboard="$UPDATED_LEADERBOARD" '
            /<!-- LEADERBOARD_START -->/ {print; print new_leaderboard; skip=1; next}g
            /<!-- LEADERBOARD_END -->/ {skip=0}
            !skip' $README_FILE > temp.md && mv temp.md $README_FILE

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automated leaderboard update for $COMMITTER in $MONTH"
          git push
